[supervisord]
nodaemon=true
logfile=/dev/null
pidfile=/var/run/supervisord.pid

[program:octane]
command=frankenphp run --config Caddyfile --workers 4
directory=/app
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
user=www-data

[program:queue-worker]
command=php artisan queue:work redis --sleep=3 --tries=3 --timeout=90
directory=/app
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
user=www-data
